# Generated by Django 4.2.14 on 2024-09-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_type',
            new_name='location_state',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='Management',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='user',
        ),
    ]
