# Generated by Django 4.2.14 on 2024-09-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_agent_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='availability',
            field=models.CharField(choices=[('Selling', 'Selling'), ('Rent', 'Rent')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
