# Generated by Django 4.2.14 on 2024-09-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_management_address_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='details',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='details',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
