# Generated by Django 4.2.14 on 2024-10-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_management_details_property_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='associated_agent',
            field=models.ManyToManyField(to='main.agent'),
        ),
        migrations.AddField(
            model_name='management',
            name='features',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
