# Generated by Django 4.2.14 on 2024-10-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_management_associated_agent_management_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management',
            old_name='no_of_block',
            new_name='no_of_bathrooms',
        ),
        migrations.RenameField(
            model_name='management',
            old_name='no_of_flat',
            new_name='no_of_bedrooms',
        ),
    ]
