# Generated by Django 4.2.14 on 2024-10-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_no_of_block_management_no_of_bathrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
