# Generated by Django 4.2.14 on 2024-10-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_propertycontactmessage_managementcontactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementcontactmessage',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='propertycontactmessage',
            name='phone',
        ),
        migrations.AddField(
            model_name='managementcontactmessage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='propertycontactmessage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
